---
- name: Update APT Cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Apache Web Server
  ansible.builtin.apt:
    name: "{{ apache_package }}"
    state: present

- name: Start and Enable Apache Service
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
- name: Copy Custom Web Page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Restart Apache

