- name: Create AWS VPC
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: my_vpc
        cidr_block: 10.0.0.0/16
        state: present
        region: "{{ region }}"
        tags:
          Name: my_vpc

    - name: Create Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: 10.0.1.0/24
        state: present
        region: "{{ region }}"
        tags:
          Name: my_subnet
        zone: "{{ zone }}"