---
- name: iterate over index
  hosts: all
  tasks:
    - name: iterate using index
      debug:
       msg: "The book {{ item.0 }} is {{ item.1 }}"
      with_indexed_items:
       - "Blue"
       - "Red"
       - "Green"
       - "White"