---
- name: Apache Web Server Install
  hosts: all
  become: true

  tasks:
  - include_vars: vars.yaml
  - name: install apache2
    apt: 
      name={{package_name}}
      update_cache=yes
      state=latest