- name: Join Worker Nodes to Cluster
  hosts: workers
  become: true
  vars_files:
    - vars.yaml

  tasks:
    - name: Join worker nodes
      command: "{{ hostvars['master']['worker_join_cmd'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
        