- name: Update system packages (RHEL-based)
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
  become: yes

- name: Install required dependencies (RHEL-based)
  dnf:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == "RedHat"
  become: yes

- name: Add Kubernetes repository (RHEL-based)
  shell: |
    cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version[:4] }}/rpm/
    enabled=1
    gpgcheck=1
    gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version[:4] }}/rpm/repodata/repomd.xml.key
    EOF
  when: ansible_os_family == "RedHat"
  become: yes

- name: Install Kubernetes components (RHEL-based)
  dnf:
    name:
      - kubelet-{{ kubernetes_version }}-0
      - kubeadm-{{ kubernetes_version }}-0
      - kubectl-{{ kubernetes_version }}-0
    state: present
    disable_excludes: kubernetes
  when: ansible_os_family == "RedHat"
  become: yes

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat"
  become: yes

- name: Disable swap (RHEL-based)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: yes

- name: Remove swap entry from /etc/fstab (RHEL-based)
  replace:
    path: /etc/fstab
    regexp: '^.*\sswap\s.*$'
    replace: ''
  when: ansible_swaptotal_mb > 0
  become: yes
