- name: Setup Kubernetes Cluster
  hosts: kubernetes
  become: true
  vars_files:
    - vars.yaml
  roles:
    - common

- name: Initialize Kubernetes Master
  hosts: master
  become: true
  vars_files:
    - vars.yaml
  roles:
    - master

- name: Join Worker Nodes
  hosts: workers
  become: true
  vars_files:
    - vars.yaml
  roles:
    - workers
